# Generated by Django 2.1.1 on 2018-09-27 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('total_consumption_kwh_low', models.FloatField(blank=True, null=True)),
                ('total_consumption_kwh_high', models.FloatField(blank=True, null=True)),
                ('total_production_kwh_low', models.FloatField(blank=True, null=True)),
                ('total_production_kwh_high', models.FloatField(blank=True, null=True)),
                ('current_consumption_kw', models.FloatField(blank=True, null=True)),
                ('current_production_kw', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('total_consumption_m3', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identification_string', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'electricity'), (2, 'gas')])),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram', models.BinaryField(blank=True, null=True)),
                ('upload_timestamp', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gasreading',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prikmeter.Meter'),
        ),
        migrations.AddField(
            model_name='electricityreading',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prikmeter.Meter'),
        ),
    ]
